(()=>{
const D=DISCOVERY_DATA,q=document.querySelector('#globalQuery'),content=document.querySelector('#searchContent'),tabs=document.querySelector('.search-tabs'),clear=document.querySelector('#clearQuery');
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fa=n=>`<i class="icon fa-solid fa-${n}" aria-hidden="true"></i>`;
const norm=s=>String(s||'').toLocaleLowerCase('tr').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll('ı','i');
const params=new URLSearchParams(location.search),allowed=['ana-1.html','ana-1.html','ana-1.html','ana-1.html'];
const back=allowed.includes(params.get('donus'))?params.get('donus'):'ana-1.html';document.querySelector('#searchBack').href=back;
let type=params.get('tur')==='sef'?'sef':'all';q.value=params.get('q')||'';
const types=[['all','Tümü'],['tarif','Tarifler'],['sef','Şefler'],['video','Videolar'],['tip','Püf Noktaları']];
const items=[...D.recipes.map(r=>({...r,type:'tarif',meta:`${r.minutes} dk · ${r.category}`})),...D.chefs.map(c=>({...c,title:c.name,type:'sef',meta:c.specialty})),...D.videos.map(v=>({...v,type:'video',meta:`${v.time} · ${v.views} izlenme`})),...D.tips.map(t=>({...t,type:'tip',meta:t.reads||'Püf Noktaları'}))];
function history(){try{const a=JSON.parse(localStorage.getItem('dada-general-search')||'[]');return Array.isArray(a)?a.filter(x=>typeof x==='string').slice(0,6):[]}catch{return []}}
function save(){const s=q.value.trim();if(s.length>1)try{localStorage.setItem('dada-general-search',JSON.stringify([s,...history().filter(x=>x!==s)].slice(0,6)))}catch{}}
function popular(){return `<section class="search-section"><h2>Popüler aramalar</h2><div class="chips">${D.popular.map(s=>`<button class="chip" data-term="${e(s)}">${e(s)}</button>`).join('')}</div></section>`}
function render(){const value=q.value.trim(),key=norm(value);clear.hidden=!value;tabs.hidden=!value&&type==='all';tabs.innerHTML=types.map(([v,n])=>`<button role="tab" aria-selected="${type===v}" data-type="${v}">${n}</button>`).join('');
if(!value&&type==='all'){const recent=history();content.innerHTML=`<section class="search-section"><h2>Son aramalar</h2>${recent.length?recent.map(s=>`<button class="search-recent-row" data-term="${e(s)}">${fa('clock-rotate-left')}${e(s)}</button>`).join(''):'<p class="search-count">Henüz arama yapmadın.</p>'}</section>${popular()}`;return}
const result=items.filter(r=>(type==='all'||r.type===type)&&(!key||norm(r.title+' '+r.meta+' '+(r.author||'')).includes(key)));
content.innerHTML=`<p class="search-count" role="status">${result.length} sonuç${value?' · '+e(value):''}</p>`+(result.length?result.map(r=>{const i=items.indexOf(r),tag=r.type==='tarif'?'a':'button',attr=tag==='a'?`href="../secenekler/detay-1.html?tarif=${encodeURIComponent(r.slug)}&donus=${encodeURIComponent(back)}"`:`type="button"`;return `<${tag} ${attr} class="search-result" data-result="${i}"><div class="photo ${r.type==='sef'?'is-avatar':''}" role="img" aria-label="${e(r.title)}" style="${r.image?`background-image:url('${e(r.image)}')`:''}">${r.image?'':e(r.title[0])}</div><span class="search-result-copy"><small>${types.find(t=>t[0]===r.type)[1]}</small><strong>${e(r.title)}</strong><small>${e(r.meta)}</small></span>${fa(r.type==='video'?'play':'arrow-right')}</${tag}>`}).join(''):`<section class="search-empty">${fa('magnifying-glass')}<h2>Sonuç bulunamadı</h2><p>Yazımı kontrol et veya daha kısa bir kelime dene.</p><button class="button secondary" data-reset>Aramayı temizle</button></section>${popular()}`);
}
q.addEventListener('input',()=>{render();const u=new URL(location.href);q.value?u.searchParams.set('q',q.value):u.searchParams.delete('q');window.history.replaceState(null,'',u)});
q.addEventListener('blur',save);document.querySelector('#globalSearch').addEventListener('submit',ev=>{ev.preventDefault();save();q.blur();render()});clear.onclick=()=>{q.value='';type='all';render();q.focus()};
document.addEventListener('click',ev=>{const t=ev.target.closest('[data-term],[data-type],[data-reset],[data-result]');if(!t)return;if(t.hasAttribute('data-term')){q.value=t.dataset.term;type='all';save();render()}if(t.hasAttribute('data-type')){type=t.dataset.type;render()}if(t.hasAttribute('data-reset'))clear.click();if(t.hasAttribute('data-result')){save();const r=items[Number(t.dataset.result)];if(r.type!=='tarif'){const dialog=document.querySelector('.search-detail');dialog.querySelector('.search-detail-content').innerHTML=`${r.image?`<div class="photo" style="background-image:url('${e(r.image)}')"></div>`:''}<h2>${e(r.title)}</h2><p>${e(r.meta)}</p><p>${r.type==='video'?'Video oynatma kaynağı henüz eklenmedi.':r.type==='sef'?'Şef profili önizlemesi.':'Bu içeriğin tam metni bu önizlemede henüz yer almıyor.'}</p>`;dialog.showModal()}}});
const dialog=document.querySelector('.search-detail');document.querySelector('#closeDetail').onclick=()=>dialog.close();dialog.addEventListener('click',ev=>{if(ev.target===dialog){const r=dialog.getBoundingClientRect();if(ev.clientY<r.top)dialog.close()}});
render();requestAnimationFrame(()=>q.focus({preventScroll:true}));
})();
