/* Alternative decision structures. All matches use the same real recipe collection. */
(()=>{
const key=document.body.dataset.edition,cfg=HOME_SETS[key];if(!cfg)return;
const q=s=>document.querySelector(s),fa=n=>`<i class="icon fa-solid fa-${n}" aria-hidden="true"></i>`,short=r=>r.title.split('|')[0].trim(),norm=s=>s.toLocaleLowerCase('tr-TR');
const back=location.pathname.split('/').pop(),searchURL=`arama.html?donus=${back}`,detail=r=>`../secenekler/detay-1.html?tarif=${r.slug}&donus=${back}`;
const pic=r=>`<div class="photo" style="background-image:url('${r.image}')" role="img" aria-label="${esc(short(r))}"></div>`;
const seed=DATA.recipes[cfg.photo],root=q('.six-hero'),search=`<a class="six-search a-global-search set-search six-hero-group" href="${searchURL}">${fa('magnifying-glass')}<span>Tarif, şef, video ara</span></a>`;
const headings={'7':['Vaktin kadar bir sofra','Ne kadar vaktin var?'],'8':['Sofrana yeni bir yön','Canın ne çekiyor?'],'9':['Karar vermek kolaylaşsın','Hangisini pişirsek?'],x1:['Mutfağın başlangıç noktası','Bugün ne pişirsem?'],x2:['Bir fikir, bir sonraki adım','Sofrana bir yol bul.'],x3:['Bugünkü kararın','Hafif mi, doyurucu mu?'],x4:['İhtiyacından başla','Nasıl pişireceğiz?'],x5:['Gör, seç, pişir','Bir fikir aç.'],x6:['Sofra defteri','Bugünün planı ne?']};
const [label,title]=["Sofrana bir fikir","Ne pişirsem?"],ings=[['Patates','seedling'],['Tavuk','drumstick-bite'],['Yumurta','egg'],['Peynir','cheese'],['Limon','lemon'],['Pirinç','bowl-rice'],['Lahana','leaf'],['Ayva','apple-whole']];
const selected=new Set();let limit=0,cuisine='',category='',offset=0;
const answer=r=>`<a class="set-answer six-hero-group" href="${detail(r)}"><span><small>Başlamak için bir öneri</small><strong>${esc(short(r))}</strong></span>${fa('arrow-right')}</a>`;
root.innerHTML=`<div class="purpose-banner new-banner"><div class="purpose-backdrop">${pic(seed)}</div><div class="purpose-veil"></div><div class="set-intro"><span class="purpose-eyebrow six-hero-group">${label}</span><h1 class="six-hero-group">${title}</h1>${search}</div><div class="set-decision six-hero-group"></div>${answer(seed)}</div><section class="decision-kitchen new-kitchen" data-six-block="ingredients"><div class="kitchen-heading"><h2>Elinde ne var?</h2></div><p class="kitchen-suggestion">Malzemeni seç, sofrana bir fikir bulalım.</p><div class="kitchen-ingredients" aria-label="Malzemeler" role="group">${ings.map(([n,i])=>`<button data-set-ingredient="${n}" aria-pressed="false">${fa(i)}<span>${n}</span><i class="icon fa-solid fa-check kitchen-check" aria-hidden="true"></i></button>`).join('')}</div><div class="kitchen-result-head"><output data-set-count aria-live="polite"></output><button class="text-link" data-set-reset hidden>Temizle</button></div><div class="kitchen-previews" data-set-preview></div><a class="button kitchen-submit" data-set-submit href="../secenekler/liste-1.html">Tarifleri gör ${fa('arrow-right')}</a></section>`;
const decision=q('.set-decision'),kitchen=q('.new-kitchen');
if(key==='7')decision.innerHTML=`<div class="time-window"><span class="time-symbol">${fa('clock')}</span><span>Bugün mutfağa<br>ayıracağın süre</span></div><div class="set-options" aria-label="Süre seç">${[30,60,120].map(n=>`<button data-set-time="${n}" aria-pressed="false"><strong>${n}</strong><span>dk altı</span></button>`).join('')}</div>`;
if(key==='8')decision.innerHTML=`<div class="cuisine-window">${pic(seed)}</div><div class="cuisine-options" aria-label="Dünya mutfağı seç">${[['yunan-mutfagi','Yunan'],['cin-mutfagi','Çin'],['turk-mutfagi','Türk']].map(([id,n])=>`<button data-set-cuisine="${id}" aria-pressed="false">${n}</button>`).join('')}</div>`;
if(key==='9')decision.innerHTML='<div class="decision-pair"></div><button class="set-next" data-set-pair>İki yeni fikir '+fa('shuffle')+'</button>';
const top=document.createElement('a');top.href=searchURL;top.className='icon-button a-header-search';top.setAttribute('aria-label','Genel aramayı aç');top.innerHTML=fa('magnifying-glass');top.hidden=true;q('.top-actions').prepend(top);
const drawer=openSiteDrawer;openSiteDrawer=function(){drawer();q('.drawer-top').insertAdjacentHTML('afterend',`<a class="drawer-row" href="${searchURL}">${fa('magnifying-glass')}<span>Tarif, şef, video ara</span></a>`)};
A_CHEFS.mount(q('.six-chefs'),{back,theme:'light'});
function matches(r){return [...selected].every(n=>r.ingredients.some(i=>norm(i.name).includes(norm(n))))&&(!limit||r.minutes<limit)&&(!category||(PARITY.recipes[r.slug]?.facets?.kategori||[]).includes(category))&&(!cuisine||(PARITY.recipes[r.slug]?.facets?.mutfak||[]).includes(cuisine));}
function update(){q('.new-kitchen').dataset.hasSelection=String(!!(selected.size||limit||cuisine||category));document.querySelectorAll('[data-set-category]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.setCategory===category));const found=[seed,...DATA.recipes.filter(r=>r!==seed)].filter(matches),picks=found.slice(0,3);document.querySelectorAll('[data-set-ingredient]').forEach(b=>b.setAttribute('aria-pressed',selected.has(b.dataset.setIngredient)));root.querySelectorAll('[data-set-time]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.setTime)===limit));root.querySelectorAll('[data-set-cuisine]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.setCuisine===cuisine));q('[data-set-count]').textContent=selected.size?`${selected.size} malzeme · ${found.length} tarif`:limit?`${limit} dakikadan kısa ${found.length} fikir`:cuisine||category?`${found.length} tarifle başlayabilirsin`:'Sofrana bir başlangıç';q('[data-set-reset]').hidden=!(selected.size||limit||cuisine||category);q('[data-set-preview]').innerHTML=picks.length?picks.map(r=>`<a class="kitchen-mini" href="${detail(r)}">${pic(r)}<strong>${esc(short(r))}</strong><small>${r.minutes} dk</small></a>`).join(''):'<div class="kitchen-empty"><strong>Bu seçimle tarif bulunamadı.</strong><span>Bir malzemeyi çıkar ya da seçimi temizle.</span></div>';const params=new URLSearchParams();if(selected.size)params.set('malzeme',[...selected].join(','));if(limit){for(const v of (limit===30?['15','15-30']:limit===60?['15','15-30','30-45','45-60']:['15','15-30','30-45','45-60','60-120']))params.append('sure[]',v);}if(cuisine)params.set('mutfak[]',cuisine);if(category)params.set('kategori[]',category);q('[data-set-submit]').href='../secenekler/liste-1.html?'+params;
const pair=q('.decision-pair');if(pair){const list=found.length?found:DATA.recipes;pair.innerHTML=[list[offset%list.length],list[(offset+1)%list.length]].map(r=>`<a class="pair-idea" href="${detail(r)}">${pic(r)}<span><small>${r.minutes} dk</small><strong>${esc(short(r))}</strong>${fa('arrow-right')}</span></a>`).join('');}window.dispatchEvent(new Event('six:layout'));}
document.addEventListener('click',e=>{const b=e.target.closest('[data-set-ingredient]');if(b){const n=b.dataset.setIngredient;selected.has(n)?selected.delete(n):selected.add(n);update();}const t=e.target.closest('[data-set-time]');if(t){limit=limit===Number(t.dataset.setTime)?0:Number(t.dataset.setTime);update();}const c=e.target.closest('[data-set-cuisine]');if(c){cuisine=cuisine===c.dataset.setCuisine?'':c.dataset.setCuisine;update();}const cat=e.target.closest('[data-set-category]');if(cat){category=category===cat.dataset.setCategory?'':cat.dataset.setCategory;document.querySelectorAll('[data-set-category]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.setCategory===category));update();}if(e.target.closest('[data-set-reset]')){selected.clear();limit=0;cuisine='';category='';update();}if(e.target.closest('[data-set-pair]')){offset+=2;update();}});
const old=syncHeader;removeEventListener('scroll',old);removeEventListener('resize',old);motion.removeEventListener('change',old);
syncHeader=function(){const bar=q('.topbar'),b=bar.getBoundingClientRect(),first=q('.y-first')||q('.set-intro .purpose-eyebrow');if(!first)return;const r=first.getBoundingClientRect(),limit=Math.max(1,r.top+scrollY-b.height-8),alpha=motion.matches?Number(scrollY>=Math.min(48,limit)):Math.min(1,scrollY/Math.min(48,limit));bar.style.setProperty('background-color',`color-mix(in srgb,var(--tomato) ${alpha*100}%,transparent)`,'important');bar.dataset.alpha=alpha.toFixed(3);bar.classList.toggle('is-solid',alpha>=.999);root.querySelectorAll('.six-hero-group').forEach(g=>g.style.visibility=g.getBoundingClientRect().top<b.bottom+8?'hidden':'');top.hidden=!(alpha>=.999&&q('.new-banner').getBoundingClientRect().bottom<=b.bottom);if(window.Y_SCROLL)window.Y_SCROLL();};addEventListener('scroll',syncHeader,{passive:true});addEventListener('resize',syncHeader);document.fonts.ready.then(syncHeader);update();syncHeader();window.SET_HOME={root,kitchen,decision,pic,search,detail,fa,short,seed,update};
})();
