/* Composition adapters: move source nodes; preserve every source handler and datum. */
(()=>{if(page!=='tarif-detay')return;const n=+document.body.dataset.choice,q=s=>document.querySelector(s),main=q('.detail-main'),hero=q('.detail-hero'),copy=q('.detail-cover-copy'),ingredients=q('.ingredient-section'),method=q('.method-section');document.body.classList.add('detail-study');ingredients.id='malzemeler';
function anchors(){const nav=document.createElement('nav');nav.className='ld-detail-nav segmented';nav.setAttribute('aria-label','Tarif bölümleri');nav.innerHTML='<a href="#malzemeler">Malzemeler</a><a href="#adimlar">Yapılış</a><a href="#yorumlar">Yorumlar</a>';q('.description-wrap').after(nav);return nav;}
if(n===2){q('.sheet-grip').after(copy);anchors();}
if(n===3){const tabs=document.createElement('nav');tabs.className='ld-detail-nav segmented';tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Tarif içeriği');tabs.innerHTML=['Malzemeler','Yapılış','Hakkında'].map((t,i)=>`<button role="tab" id="ld-tab-${i}" aria-controls="ld-pane-${i}" aria-selected="${i===0}" data-detail-tab="${i}">${t}</button>`).join('');q('.description-wrap').after(tabs);const panes=[0,1,2].map(i=>{const el=document.createElement('div');el.className='ld-detail-pane';el.id=`ld-pane-${i}`;el.setAttribute('role','tabpanel');el.setAttribute('aria-labelledby',`ld-tab-${i}`);el.hidden=i!==0;return el});tabs.after(...panes);panes[0].append(ingredients);panes[1].append(method);for(const el of [...main.children])if(el.matches('.recipe-metadata,.recipe-note,.recipe-tags,.nutrition,.skills'))panes[2].append(el);function select(i){panes.forEach((p,j)=>p.hidden=i!==j);tabs.querySelectorAll('button').forEach((b,j)=>{b.setAttribute('aria-selected',i===j);b.tabIndex=i===j?0:-1});applyProse();syncPhotoReadability()}tabs.addEventListener('click',e=>{const b=e.target.closest('[data-detail-tab]');if(b)select(+b.dataset.detailTab)});tabs.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let i=+document.activeElement.dataset.detailTab;i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;select(i);tabs.children[i].focus()});select(0);window.LD_SELECT_TAB=select;}
if(n===4){const steps=q('.steps'),items=[...steps.children],controls=document.createElement('div');controls.className='ld-step-controls';controls.innerHTML=`<button class="icon-button" data-ld-step="-1" aria-label="Önceki adım">${icon('back')}</button><output aria-live="polite">1 / ${items.length}</output><button class="icon-button" data-ld-step="1" aria-label="Sonraki adım">${icon('arrow')}</button>`;steps.before(controls);let index=0;function update(){index=Math.round(steps.scrollLeft/(items[0].getBoundingClientRect().width+16));controls.querySelector('output').textContent=`${index+1} / ${items.length}`;controls.children[0].disabled=index===0;controls.children[2].disabled=index===items.length-1;}controls.addEventListener('click',e=>{const b=e.target.closest('[data-ld-step]');if(b){const target=items[Math.max(0,Math.min(items.length-1,index+Number(b.dataset.ldStep)))];steps.scrollTo({left:target.offsetLeft-items[0].offsetLeft,behavior:motion.matches?'instant':'smooth'})}});steps.addEventListener('scroll',update,{passive:true});update();}
if(n===5){const photo=q('.hero-gallery-open .photo');hero.style.backgroundImage=`var(--web-hero-overlay),${`url("${photo.dataset.photoSrc}")`}`;q('.sheet-grip').after(copy);ingredients.classList.add('ld-prep-surface');const top=q('.shopping-all');q('.ingredient-progress').after(top);}
if(n===6){hero.append(q('.recipe-facts'));q('.sheet-grip').after(copy);const nav=anchors();nav.after(method);}
requestAnimationFrame(()=>{applyTypeRoles();applyProse();syncPhotoReadability();syncHeader();window.LD_READY=true;});})();
