(()=>{const {n,q,fa}=LDX,main=q('.list-editorial'),tools=q('.list-tools'),bar=q('.result-bar'),banner=q('.list-banner'),content=q('.list-content');document.body.classList.add('lx',`lx${n}`);const names=['Lezzet akışı','Seçim destesi','Görsel pano','Kategori sahneleri','Mutfak rotası','Karar masası'];let deck=0;const original=renderResults;
const stage=document.createElement('section');stage.className='lx-opening';stage.innerHTML=`<div class="lx-opening-photo" style="background-image:url('${DATA.recipes[[1,4,8,2,0,13][n-1]].image}')"></div><div class="lx-opening-copy"><span class="eyebrow">Tarifler</span><h1>${names[n-1]}</h1></div>`;banner.replaceWith(stage);tools.classList.remove('content-panel');q('.view-toggle').remove();q('.theme-expander').classList.add('lx-themes');
if([1,2].includes(n)){stage.append(tools,bar);main.prepend(stage);content.prepend(q('.lx-themes'));}else if(n===5){stage.append(tools);}
if(n===6)KARAR_PANEL.mount(tools,()=>{resultPage=1;renderResults()});
const cuisines=PARITY.list.groups.find(g=>g.key==='mutfak');if(n===5){const atlas=document.createElement('div');atlas.className='lx-atlas';const available=(cuisines?.options||[]).filter(o=>DATA.recipes.some(r=>matchesFacet(r,'mutfak',[o.value])));atlas.innerHTML=`<div class="lx-globe" aria-hidden="true">${fa('earth-americas')}</div><p>Bugün hangi mutfak?</p><div class="lx-countries"><button class="chip active" data-lx-cuisine="">Tüm mutfaklar</button>${available.map(o=>`<button class="chip" data-lx-cuisine="${esc(o.value)}">${esc(facetLabel('mutfak',o.value))}</button>`).join('')}</div><output class="lx-country-caption">Dünyadan tarifler</output>`;stage.append(atlas);atlas.addEventListener('click',e=>{const b=e.target.closest('[data-lx-cuisine]');if(!b)return;facetState.mutfak=b.dataset.lxCuisine?[b.dataset.lxCuisine]:[];q('.lx-country-caption').textContent=b.textContent;atlas.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));resultPage=1;renderResults();const first=current()[0];if(first)stage.querySelector('.lx-opening-photo').style.backgroundImage=`url('${first.image}')`;});}
function current(){let rs=filteredRecipes().filter(r=>n!==6||KARAR_PANEL.matches(r));if(sort==='en_hizli')rs.sort((a,b)=>a.minutes-b.minutes);if(sort==='en_cok_puanlanan'||sort==='puan')rs.sort((a,b)=>Number(b.rating)-Number(a.rating));if(sort==='en_yeni')rs.sort((a,b)=>recipeDate(b)-recipeDate(a));return rs;}
function shelf(){const rs=DATA.recipes.filter(r=>saved.includes(r.slug));return `<section class="lx-saved"><div class="section-heading-row"><h2>Seçtiklerin</h2><span>${rs.length} tarif</span></div>${rs.length?`<div class="lx-rail">${rs.map(card).join('')}</div>`:'<p>Kaydettiğin tarifler burada birikir.</p>'}</section>`;}
renderResults=function(){original();const all=current(),root=q('#results');q('#resultCount').innerHTML=`<b>${all.length} tarif</b> bulundu`;q('#pagination').innerHTML='';root.className='recipe-list lx-results';if(!all.length){root.innerHTML=`<div class="empty">${fa('magnifying-glass')}<h2>Tarif bulunamadı</h2><p>${n===6?'Kriterleri gevşet: süreyi uzat veya bir sınırı kaldır.':'Bir sınırı kaldır veya başka bir tarif ara.'}</p><button class="button" data-clear>Tümünü Temizle</button></div>`;LDX.finish();return;}
if(n===1)root.innerHTML=all.map((r,i)=>`<section class="lx-scene">${editorialHero(r,'','lx-cover')}<span class="lx-scene-count">${i+1} / ${all.length}</span></section>`).join('')+`<div class="lx-end"><h2>Tariflerin sonuna geldin</h2><button class="button secondary" data-lx-top>Başa dön</button></div>`;
if(n===2){deck=Math.min(deck,all.length-1);root.innerHTML=`<div class="lx-deck">${all.slice(deck,deck+3).map((r,i)=>`<div class="lx-deck-card" style="--depth:${i}" ${i?'inert aria-hidden="true"':''}>${editorialHero(r,'','lx-cover')}</div>`).reverse().join('')}</div><div class="lx-deck-actions"><button class="button secondary" data-lx-pass>${fa('arrow-right')} Geç</button><output>${deck+1} / ${all.length}</output><button class="button" data-save="${all[deck].slug}">${fa('bookmark')} Kaydet</button></div>${shelf()}`;const el=q('.lx-deck');let start=0;el.addEventListener('touchstart',e=>start=e.touches[0].clientX,{passive:true});el.addEventListener('touchend',e=>{const d=e.changedTouches[0].clientX-start;if(Math.abs(d)>65){if(d>0)q('.lx-deck-actions [data-save]').click();else pass();}},{passive:true});}
if(n===3)root.innerHTML=`<div class="lx-masonry">${all.map(card).join('')}</div><div class="lx-end">${all.length} tarifin tamamını gördün.</div>`;
if(n===4){const groups=[...new Set(all.map(r=>r.category))];root.innerHTML=groups.map(c=>{const rs=all.filter(r=>r.category===c);return `<section class="lx-category-scene"><header style="background-image:var(--web-hero-overlay),url('${rs[0].image}')"><span class="eyebrow">${rs.length} tarif</span><h2>${esc(c)}</h2><button class="chip" data-lx-category="${esc(c)}">Bu kategoriyi keşfet ${fa('arrow-right')}</button></header><div class="lx-rail">${rs.map(card).join('')}</div></section>`}).join('')+'<div class="lx-end">Bütün kategorileri gördün.</div>';}
if(n===5)root.innerHTML=`<div class="lx-route-results">${all.map((r,i)=>`<div class="lx-stop"><span class="lx-stop-number">${String(i+1).padStart(2,'0')}</span>${card(r)}</div>`).join('')}</div><div class="lx-end">Bu rotadaki ${all.length} tarif burada.</div>`;
if(n===6)root.innerHTML=`<div class="lx-comparison">${all.map(r=>`<div class="lx-compare-row">${card(r)}<span class="lx-ingredient-count">${r.ingredients.length} malzeme</span></div>`).join('')}</div><div class="lx-end">Seçimine uyan ${all.length} tarif.</div>`;
LDX.finish();};function pass(){const all=current();if(deck<all.length-1)deck++;else{deck=0;toast('Destenin sonu · İlk tarife döndün')}renderResults();}
document.addEventListener('click',e=>{if(e.target.closest('[data-lx-pass]'))pass();if(e.target.closest('[data-lx-top]'))scrollTo({top:0,behavior:motion.matches?'instant':'smooth'});const c=e.target.closest('[data-lx-category]');if(c){category=c.dataset.lxCategory;renderResults();tools.scrollIntoView({block:'start',behavior:'smooth'})}if(e.target.closest('[data-clear]')&&n===6)KARAR_PANEL.clear();if(e.target.closest('[data-save]')&&n===2)setTimeout(()=>{const r=q('.lx-saved');if(r){r.outerHTML=shelf();LDX.finish()}},100);});
q('.lx-themes').querySelectorAll('button').forEach(b=>b.type='button');q('#filterForm').prepend(q('.lx-themes'));window.LX={current,pass};LDX.header();renderResults();})();
