/* The new family inherits A's full page and shared components; only its decision composition changes. */
(()=>{
const mode=Number(document.body.dataset.concept);if(!mode)return;
const q=s=>document.querySelector(s),fa=n=>`<i class="icon fa-solid fa-${n}" aria-hidden="true"></i>`,short=r=>r.title.split('|')[0].trim(),norm=s=>s.toLocaleLowerCase('tr-TR');
const back=location.pathname.split('/').pop(),url=`arama.html?donus=${encodeURIComponent(back)}`,detail=r=>`../secenekler/detay-1.html?tarif=${encodeURIComponent(r.slug)}&donus=${back}`;
const pic=(r,cls='')=>`<div class="photo ${cls}" role="img" aria-label="${esc(short(r))}" style="background-image:url('${r.image}')"></div>`;
const hour=new Date().getHours();let meal=hour<11?'kahvalti':hour<17?'ogle-yemegi':'aksam-yemegi';
const meals={'kahvalti':'Kahvaltı','ogle-yemegi':'Öğle','aksam-yemegi':'Akşam'},mealTitle=()=>meal==='kahvalti'?'Kahvaltıda ne pişirsek?':`${meals[meal]} için ne pişirsek?`;
const ingredients=[['Patates','seedling'],['Tavuk','drumstick-bite'],['Yumurta','egg'],['Peynir','cheese'],['Limon','lemon'],['Pirinç','bowl-rice'],['Lahana','leaf'],['Ayva','apple-whole']];
const selected=new Set(),root=q('.six-hero');let active=0;const baseIndex={2:9,3:14,4:12,5:17,6:18};
document.body.dataset.kitchenLayout='rail';
const topSearch=document.createElement('a');topSearch.href=url;topSearch.className='icon-button a-header-search';topSearch.setAttribute('aria-label','Genel aramayı aç');topSearch.innerHTML=fa('magnifying-glass');topSearch.hidden=true;q('.top-actions').prepend(topSearch);
const oldDrawer=openSiteDrawer;openSiteDrawer=function(){oldDrawer();q('.drawer-top').insertAdjacentHTML('afterend',`<a class="drawer-row a-drawer-search" href="${url}">${fa('magnifying-glass')}<span>Tarif, şef, video ara</span></a>`)};
A_CHEFS.mount(q('.six-chefs'),{back,theme:'dark'});
const seed=DATA.recipes[baseIndex[mode]],search=`<a class="six-search a-global-search family-search six-hero-group" href="${url}" aria-label="Genel aramayı aç">${fa('magnifying-glass')}<span>Tarif, şef, video ara</span></a>`;
const headings={2:mealTitle(),3:'Ne pişirsem? Bir fikir seç.',4:'Ne pişirsem?',5:'Ne pişirsem?',6:'Bugün<br>ne pişirsem?'};
const eyebrows={2:hour<11?'Günaydın':hour<17?'Merhaba':'İyi akşamlar',3:'Sofrana bir fikir',4:'Sofran burada başlar',5:'Elindekilerden başlayalım',6:'Bugünün mutfağı'};
const answer=(r,label='Başlamak için bir öneri')=>`<a class="purpose-answer six-hero-group" href="${detail(r)}"><span><small data-family-label>${label}</small><strong data-family-title>${esc(short(r))}</strong></span>${fa('arrow-right')}</a>`;
root.innerHTML=`<div class="purpose-banner family-banner">${pic(seed,'purpose-backdrop')}<div class="purpose-veil"></div><div class="purpose-title"><div class="purpose-copy six-hero-group"><span class="purpose-eyebrow">${eyebrows[mode]}</span><h1>${headings[mode]}</h1></div>${search}</div>${answer(seed)}</div><section class="decision-kitchen" data-six-block="ingredients" aria-label="Ne Pişirsem malzeme seçimi"><div class="family-picker"><div class="kitchen-heading"><h2>Elinde ne var?</h2></div><p class="kitchen-suggestion">${mode===5?'Bir malzeme seç, sofran şekillensin.':'Malzemelerini seç, birlikte karar verelim.'}</p><div class="kitchen-ingredients" role="group" aria-label="Malzemeler">${ingredients.map(([n,i])=>`<button type="button" data-family-ingredient="${n}" aria-pressed="false">${fa(i)}<span>${n}</span><i class="icon fa-solid fa-check kitchen-check" aria-hidden="true"></i></button>`).join('')}</div></div><div class="family-results"><div class="kitchen-result-head"><output aria-live="polite" data-family-count></output><button class="text-link" data-family-reset hidden>Temizle</button></div><div class="kitchen-previews" data-family-previews></div><a class="button kitchen-submit" data-family-submit href="../secenekler/liste-1.html">Tarifleri gör ${fa('arrow-right')}</a></div></section>`;
if(mode===2){q('.family-picker').insertAdjacentHTML('afterbegin',`<div class="family-meals" role="group" aria-label="Öğün seç">${Object.entries(meals).map(([v,n])=>`<button data-family-meal="${v}" aria-pressed="${v===meal}">${n}</button>`).join('')}</div>`);q('.purpose-banner').insertAdjacentHTML('beforeend',`<div class="family-meal-photo">${pic(seed)}</div>`);}
if(mode===3){q('.purpose-answer').remove();q('.purpose-banner').insertAdjacentHTML('beforeend','<div class="family-deck" aria-label="Tarif fikirleri" tabindex="0"></div><div class="family-deck-footer"><span data-family-page></span><button class="icon-button" data-family-next aria-label="Sonraki tarif fikri">'+fa('arrow-right')+'</button></div>');}
if(mode===5){q('.purpose-banner').append(q('.family-picker'));q('.family-picker').classList.add('six-hero-group');}
if(mode===6){q('.purpose-banner').insertAdjacentHTML('beforeend',`<div class="family-cover-photo">${pic(seed)}</div>`);q('.purpose-copy .purpose-eyebrow').insertAdjacentHTML('afterend','<span class="family-cover-rule" aria-hidden="true"></span>');}
const filter=r=>[...selected].every(n=>r.ingredients.some(i=>norm(i.name).includes(norm(n))))&&(mode!==2||(PARITY.recipes?.[r.slug]?.facets?.ogun||[]).includes(meal));
function listURL(){const p=new URLSearchParams();if(selected.size)p.set('malzeme',[...selected].join(','));if(mode===2)p.set('ogun[]',meal);return '../secenekler/liste-1.html'+(p.size?'?'+p:'');}
function update(){
 const found=DATA.recipes.filter(filter),picks=[seed,...DATA.recipes.filter(r=>r!==seed)].filter(r=>found.includes(r)).slice(0,3);active=0;
 root.querySelectorAll('[data-family-ingredient]').forEach(b=>b.setAttribute('aria-pressed',selected.has(b.dataset.familyIngredient)));
 q('[data-family-count]').textContent=selected.size?`${selected.size} malzeme · ${found.length} tarif`:mode===2?`${meals[meal]} için fikirler`:'Bir malzeme seç, birlikte başlayalım';
 q('[data-family-reset]').hidden=!selected.size;q('[data-family-submit]').href=listURL();q('[data-family-submit]').setAttribute('aria-label',`${found.length} eşleşen tarifi gör`);
 q('[data-family-previews]').innerHTML=picks.length?picks.map(r=>`<a class="kitchen-mini" href="${detail(r)}">${pic(r)}<strong>${esc(short(r))}</strong><small>${r.minutes} dk</small></a>`).join(''):'<div class="kitchen-empty"><strong>Bu seçimle tarif bulunamadı.</strong><span>Bir malzemeyi çıkar veya seçimi temizle.</span></div>';
 const current=picks[0];if(mode!==3){const a=q('.purpose-answer');q('[data-family-label]').textContent=selected.size?'Bu malzemelerle':mode===2?`${meals[meal]} için bir öneri`:'Başlamak için bir öneri';q('[data-family-title]').textContent=current?short(current):'Seçimini biraz genişlet';a.href=current?detail(current):listURL();if(current){q('.purpose-backdrop').style.backgroundImage=`url('${current.image}')`;const image=q('.family-meal-photo .photo,.family-cover-photo .photo');if(image){image.style.backgroundImage=`url('${current.image}')`;image.setAttribute('aria-label',short(current));}}}
 if(mode===3){const deck=q('.family-deck');deck.innerHTML=picks.length?picks.map((r,i)=>`<a class="family-idea-card" href="${detail(r)}">${pic(r)}<span class="family-card-copy"><small>${selected.size?'Bu malzemelerle':'Pişirmek için bir fikir'} · ${r.minutes} dk</small><strong>${esc(short(r))}</strong><span>Tarife bak ${fa('arrow-right')}</span></span></a>`).join(''):'<div class="kitchen-empty">Malzeme seçimini genişlet, yeni fikirler bulalım.</div>';deck.scrollLeft=0;q('[data-family-page]').textContent=picks.length?`1 / ${picks.length} fikir`:'Yeni bir malzeme dene';q('[data-family-next]').disabled=picks.length<2;}
 if(mode===2){q('.purpose-title h1').textContent=mealTitle();root.querySelectorAll('[data-family-meal]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.familyMeal===meal));}
 window.dispatchEvent(new Event('six:layout'));
}
root.addEventListener('click',e=>{const b=e.target.closest('[data-family-ingredient]');if(b){const n=b.dataset.familyIngredient;selected.has(n)?selected.delete(n):selected.add(n);update();}if(e.target.closest('[data-family-reset]')){selected.clear();update();}const m=e.target.closest('[data-family-meal]');if(m){meal=m.dataset.familyMeal;update();}if(e.target.closest('[data-family-next]')){const d=q('.family-deck'),items=[...d.children];active=(active+1)%items.length;d.scrollTo({left:items[active].offsetLeft-items[0].offsetLeft,behavior:motion.matches?'instant':'smooth'});}});
q('.family-deck')?.addEventListener('scroll',()=>{const d=q('.family-deck'),cards=[...d.children];active=cards.reduce((best,c,i)=>Math.abs(c.offsetLeft-cards[0].offsetLeft-d.scrollLeft)<Math.abs(cards[best].offsetLeft-cards[0].offsetLeft-d.scrollLeft)?i:best,0);q('[data-family-page]').textContent=`${active+1} / ${cards.length} fikir`;},{passive:true});
// Same approved chrome, with geometry-driven visibility and a logo that never transforms.
const previous=syncHeader;removeEventListener('scroll',previous);removeEventListener('resize',previous);motion.removeEventListener('change',previous);
const banner=q('.purpose-banner');let ticking=false;
syncHeader=function(){const top=q('.topbar'),h=top.getBoundingClientRect(),first=q('.purpose-copy'),r=first.getBoundingClientRect();const limit=Math.max(1,r.top+scrollY-h.height-8),alpha=motion.matches?Number(scrollY>=Math.min(48,limit)):Math.min(1,scrollY/Math.min(48,limit));top.style.setProperty('background-color',`color-mix(in srgb,var(--tomato) ${alpha*100}%,transparent)`,'important');top.dataset.alpha=alpha.toFixed(3);top.classList.toggle('is-solid',alpha>=.999);for(const g of root.querySelectorAll('.six-hero-group'))g.style.visibility=g.getBoundingClientRect().top<h.bottom+8?'hidden':'';q('.a-header-search').hidden=!(alpha>=.999&&banner.getBoundingClientRect().bottom<=h.bottom);};
function scroll(){syncHeader();if(mode!==4)return;if(ticking)return;ticking=true;requestAnimationFrame(()=>{if(mode===4){const collapse=motion.matches?0:Math.min(160,scrollY*.32);banner.style.setProperty('--family-collapse',collapse+'px');q('.purpose-title').style.setProperty('--family-title-scale',motion.matches?1:Math.max(.88,1-scrollY/2400));}syncHeader();ticking=false;});}
addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);motion.addEventListener('change',scroll);
update();document.fonts.ready.then(scroll);scroll();
})();
