/* One shared cooking-decision component, six deliberately different entry points. */
(() => {
 const norm=s=>String(s||'').toLocaleLowerCase('tr-TR');
 const short=r=>r.title.split('|')[0].trim();
 const foods=[['Patates','seedling'],['Yumurta','egg'],['Tavuk','drumstick-bite'],['Limon','lemon'],['Peynir','cheese'],['Lahana','leaf'],['Ayva','apple-whole'],['Pirinç','bowl-rice']];
 const initial={a:4,b:9,c:1,d:17,e:12,f:24};
 const meal=()=>new Date().getHours()<11?'kahvalti':new Date().getHours()<17?'ogle-yemegi':'aksam-yemegi';
 const mealLabels={kahvalti:'Kahvaltı','ogle-yemegi':'Öğle','aksam-yemegi':'Akşam'};
 const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
 const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
 const fa=n=>`<i class="icon fa-solid fa-${n}" aria-hidden="true"></i>`;
 const keys=s=>norm(s).replaceAll('ı','i').replaceAll('ş','s').replaceAll('ğ','g').replaceAll('ç','c').replaceAll('ö','o').replaceAll('ü','u');
 function heading(mode){return {a:['Ne pişirsem?',''],b:['Dolabından başlayalım.','Ne pişirsem? Elindekilerle karar ver.'],c:['Bu öğünde ne pişirsem?',''],d:['Canın ne çekiyor?','Ne pişirsem? Önce bir kategori seç.'],e:['Bir fikirle başla.','Ne pişirsem? Kapağı seç, malzemeyle tamamla.'],f:['Ne kadar vaktin var?','Ne pişirsem? Sürene göre bul.']}[mode]}
 function render(mode,ctx){
  const r=ctx.recipes[initial[mode]],e=ctx.esc,p=ctx.photo;const [title,sub]=heading(mode);
  const titleHTML=`<div class="purpose-title"><div class="purpose-copy six-hero-group">${mode==='c'?`<span class="purpose-eyebrow">${mealLabels[meal()]} için</span>`:''}<h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div></div>`;
  let controls='';
  if(mode==='c')controls=`<div class="purpose-filters six-hero-group" aria-label="Öğün">${Object.entries(mealLabels).map(([v,n])=>`<button type="button" data-purpose-meal="${v}" aria-pressed="${v===meal()}">${n}</button>`).join('')}</div>`;
  if(mode==='f')controls=`<div class="purpose-filters six-hero-group" aria-label="Süre">${[['15','15 dk'],['30','30 dk'],['all','Fark etmez']].map(([v,n])=>`<button type="button" data-purpose-time="${v}" aria-pressed="${v==='all'}">${n}</button>`).join('')}</div>`;
  if(mode==='d')controls=`<div class="purpose-filters six-hero-group" aria-label="Kategori"><button type="button" data-purpose-category="" aria-pressed="true">Tümü</button>${[ctx.recipes[4].category,ctx.recipes[17].category,ctx.recipes[1].category].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<button type="button" data-purpose-category="${e(v)}" aria-pressed="false">${e(v)}</button>`).join('')}</div><div class="purpose-mosaic">${[17,4,14].map(i=>p(ctx.recipes[i].image)).join('')}</div>`;
  if(mode==='e')controls=`<div class="purpose-story-rail" aria-label="Tarif fikri seç">${[12,14,4].map(i=>`<button type="button" data-purpose-story="${i}" aria-pressed="false">${p(ctx.recipes[i].image)}<span>${e(short(ctx.recipes[i]))}${fa('plus')}</span></button>`).join('')}</div>`;
  if(mode==='b')controls=`<button type="button" class="purpose-start six-hero-group" data-purpose-focus>${fa('basket-shopping')} Malzemelerini seç ${fa('arrow-down')}</button>`;
  const answer=mode==='a'?`<a class="purpose-answer six-hero-group" data-purpose-answer href="${e(ctx.detail(r))}"><span><small data-purpose-answer-label>Başlamak için bir öneri</small><strong data-purpose-answer-title>${e(short(r))}</strong></span>${fa('arrow-right')}</a>`:'';
  return `<div class="purpose-banner banner-${mode}">${p(r.image,'purpose-backdrop')}<div class="purpose-veil"></div>${titleHTML}${controls}${answer}</div>${tool(ctx)}`;
 }
 function tool(ctx){const e=ctx.esc;let recent=read('six-recent-ingredients').filter(n=>foods.some(f=>f[0]===n));const ordered=[...recent,...foods.map(f=>f[0]).filter(n=>!recent.includes(n))];return `<section class="decision-kitchen" aria-label="Ne Pişirsem malzeme seçimi"><div class="kitchen-heading"><div><span class="purpose-eyebrow">Ne Pişirsem</span><h2>Elinde ne var?</h2></div><span class="kitchen-mark">${fa('wand-magic-sparkles')}</span></div><div class="kitchen-paths"><button type="button" data-kitchen-write aria-expanded="false"><span class="kitchen-path-icon">${fa('magnifying-glass')}</span><strong>Yazarak ara</strong></button><button type="button" data-kitchen-pantry><span class="kitchen-path-icon">${fa('box-open')}</span><strong>Dolapta Ne Var</strong><small>Kayıtlı dolabım</small></button><a href="${e(ctx.camera)}"><span class="kitchen-path-icon">${fa('camera')}</span><strong>Tabaktan Tarif</strong><small>Fotoğrafla bul</small></a></div><div class="kitchen-search-panel" hidden><label class="kitchen-search-label" for="kitchen-query">Yazarak ara</label>${ctx.searchHTML.replace('type="search"','id="kitchen-query" type="search"')}</div><p class="kitchen-suggestion">${recent.length?'Son kullandıkların':'Sonbahardan başla: patates, lahana, ayva'}</p><div class="kitchen-ingredients" role="group" aria-label="Malzemeler">${ordered.map(n=>`<button type="button" data-kitchen-ingredient="${e(n)}" aria-pressed="false">${fa(foods.find(f=>f[0]===n)[1])}<span>${e(n)}</span><i class="icon fa-solid fa-check kitchen-check" aria-hidden="true"></i></button>`).join('')}</div><div class="kitchen-result-head"><output aria-live="polite" data-kitchen-count></output><button class="text-link" type="button" data-kitchen-reset hidden>Temizle</button></div><div class="kitchen-previews" data-kitchen-previews></div><a class="button kitchen-submit" data-kitchen-submit href="../secenekler/liste-1.html">Tarifleri gör ${fa('arrow-right')}</a><span class="kitchen-data-note">${ctx.recipes.length} tariflik örnek koleksiyonda</span></section>`}
 function bind(mode,ctx){
  const root=document.querySelector('.six-hero'),e=ctx.esc;const selected=new Set();let limit=Infinity,category='',selectedMeal=mode==='c'?meal():'',story=null;const base=ctx.recipes[initial[mode]];
  const matches=r=>[...selected].every(n=>r.ingredients.some(i=>norm(i.name).includes(norm(n))))&&r.minutes<=limit&&(!category||r.category===category)&&(!selectedMeal||(ctx.mealFor(r)||[]).some(x=>keys(x)===selectedMeal));
  const resultLink=()=>{const p=new URLSearchParams();if(selected.size)p.set('malzeme',[...selected].join(','));if(limit!==Infinity)p.set('sure',limit);if(category)p.set('kategori',category);if(selectedMeal)p.set('ogun[]',selectedMeal);return '../secenekler/liste-1.html'+(p.size?'?'+p:'')};
  function paint(){
   const filtered=ctx.recipes.filter(matches);const order=[story||base,...[4,14,17,1,9,24,12].map(i=>ctx.recipes[i]),...ctx.recipes];const picks=[...new Set(order)].filter(r=>filtered.includes(r)).slice(0,3);
   root.querySelectorAll('[data-kitchen-ingredient]').forEach(b=>b.setAttribute('aria-pressed',selected.has(b.dataset.kitchenIngredient)));
   root.querySelector('[data-kitchen-count]').textContent=`${selected.size} malzeme · ${filtered.length} tarif`;
   root.querySelector('[data-kitchen-reset]').hidden=!selected.size&&limit===Infinity&&!category&&!selectedMeal&&!story;
   root.querySelector('[data-kitchen-previews]').innerHTML=picks.length?picks.map(r=>`<a class="kitchen-mini" href="${e(ctx.detail(r))}">${ctx.photo(r.image)}<strong>${e(short(r))}</strong><small>${r.minutes} dk</small></a>`).join(''):`<div class="kitchen-empty"><strong>Bu seçimle tarif bulunamadı.</strong><span>Bir malzemeyi çıkar veya seçimi temizle.</span></div>`;
   const submit=root.querySelector('[data-kitchen-submit]');submit.href=resultLink();submit.setAttribute('aria-label',`${filtered.length} eşleşen tarifi gör`);
   if(mode==='a'){const current=selected.size?picks[0]:base;const answer=root.querySelector('[data-purpose-answer]');root.querySelector('[data-purpose-answer-label]').textContent=selected.size?'Bu malzemelerle':'Başlamak için bir öneri';root.querySelector('[data-purpose-answer-title]').textContent=current?short(current):'Seçimini biraz genişlet';answer.href=current?ctx.detail(current):resultLink();if(current)root.querySelector('.purpose-backdrop').style.backgroundImage=`url("${current.image}")`;}
   if((mode==='c'||mode==='f')&&picks[0])root.querySelector('.purpose-backdrop').style.backgroundImage=`url("${picks[0].image}")`;if(mode==='c')root.querySelector('.purpose-title .purpose-eyebrow').textContent=selectedMeal?mealLabels[selectedMeal]+' için':'Her öğün için';
   if(selected.size)write('six-recent-ingredients',[...selected]);
   window.dispatchEvent(new Event('six:layout'));
  }
  root.addEventListener('click',event=>{const t=event.target;
   const search=t.closest('[data-kitchen-write]');if(search){const panel=root.querySelector('.kitchen-search-panel');panel.hidden=!panel.hidden;search.setAttribute('aria-expanded',!panel.hidden);if(!panel.hidden){panel.querySelector('input').focus({preventScroll:true});panel.scrollIntoView({block:'nearest',behavior:'instant'});}}
   const ingredient=t.closest('[data-kitchen-ingredient]');if(ingredient){const n=ingredient.dataset.kitchenIngredient;selected.has(n)?selected.delete(n):selected.add(n);paint()}
   if(t.closest('[data-kitchen-reset]')){selected.clear();limit=Infinity;category='';selectedMeal='';story=null;root.querySelectorAll('[data-purpose-story],[data-purpose-category],[data-purpose-time],[data-purpose-meal]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.purposeTime==='all'||b.dataset.purposeCategory===''));paint()}
   for(const kind of ['time','category','meal']){const b=t.closest(`[data-purpose-${kind}]`);if(!b)continue;const value=b.dataset['purpose'+kind[0].toUpperCase()+kind.slice(1)];if(kind==='time')limit=value==='all'?Infinity:Number(value);if(kind==='category')category=value;if(kind==='meal')selectedMeal=value;root.querySelectorAll(`[data-purpose-${kind}]`).forEach(x=>x.setAttribute('aria-pressed',x===b));paint()}
   const cover=t.closest('[data-purpose-story]');if(cover){story=ctx.recipes[Number(cover.dataset.purposeStory)];selected.clear();foods.filter(([n])=>story.ingredients.some(i=>norm(i.name).includes(norm(n)))).slice(0,2).forEach(([n])=>selected.add(n));root.querySelectorAll('[data-purpose-story]').forEach(x=>x.setAttribute('aria-pressed',x===cover));paint();root.querySelector('.kitchen-suggestion').textContent=`${short(story)} fikrinden: malzemeleri değiştirebilirsin.`;}
   if(t.closest('[data-purpose-focus]'))root.querySelector('.decision-kitchen').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth',block:'start'});
   if(t.closest('[data-kitchen-pantry]')){const saved=read('six-pantry');ctx.sheet('Dolapta Ne Var',`<p>Bu cihazdaki dolabın · yerel önizleme</p><div class="widget-ingredient-list">${foods.map(([n,icon])=>`<button class="chip" data-pantry-item="${e(n)}" aria-pressed="${saved.includes(n)}">${fa(icon)} ${e(n)}</button>`).join('')}</div><div class="sheet-actions"><button class="button" data-pantry-use>Kaydet ve kullan</button></div>`);}
  });
  document.addEventListener('click',event=>{const b=event.target.closest('[data-pantry-item]');if(b)b.setAttribute('aria-pressed',b.getAttribute('aria-pressed')!=='true');if(event.target.closest('[data-pantry-use]')){const chosen=[...document.querySelectorAll('[data-pantry-item][aria-pressed=true]')].map(x=>x.dataset.pantryItem);write('six-pantry',chosen);selected.clear();chosen.forEach(n=>selected.add(n));document.querySelector('dialog[open]')?.close();paint()}});
  paint();
 }
 window.SIX_HERO={render,bind};
})();
