/* Six compositions on the unchanged En sade source components. */
(()=>{
const mode=document.body.dataset.six;if(!mode)return;
const q=(s,r=document)=>r.querySelector(s),all=(s,r=document)=>[...r.querySelectorAll(s)];
const filename=location.pathname.split('/').pop()||`ana-${mode}.html`,camera=`tabaktan-tarif.html?donus=${filename}`;
const detail=r=>`detay-1.html?tarif=${encodeURIComponent(r.slug)}&donus=${filename}`;
ICONS.tip='lightbulb';ICONS['hand-pointer']='hand-pointer';ICONS.sliders='sliders';
const media=url=>window.SIX_MEDIA?.map?.[url]||url;
for(const r of DATA.recipes){const m=HOME_MEDIA.recipes.find(x=>x.slug===r.slug);if(m)r.image=m.image;}
for(const v of WEB.videos)v.image=media(v.image);
const picture=(url,cls='')=>`<div class="photo ${cls}" role="img" aria-label="Yemek fotoğrafı" style="background-image:url('${esc(media(url))}')"></div>`;
const searchHTML=`<form class="six-search" id="sixSearch" role="search" action="liste-1.html"><input type="search" name="q" aria-label="Tarif adı ara" placeholder="Tarif adı ara… (ör. mercimek çorbası)" autocomplete="off"><button type="button" class="icon-button" data-six-clear aria-label="Aramayı temizle" hidden>${icon('close')}</button><button class="icon-button" aria-label="Ara">${icon('arrow')}</button><button type="button" class="icon-button" data-voice="sixSearch" aria-label="Sesli arama">${icon('mic')}</button></form>`;
function heading(title,href='',label='Tümünü gör',extra=''){return `<div class="section-heading-row six-heading"><h2>${esc(title)}</h2><a class="six-see" href="${href}" ${extra} aria-label="${esc(title)} ${label}"><span>${label}</span>${icon('arrow')}</a></div>`;}
function openVideo(i){const v=WEB.videos[i];if(!v)return;sheet('Video Mutfağı',`<div class="six-video-detail">${picture(v.image)}<h3>${esc(v.title)}</h3><p>${esc(v.time)} · ${esc(v.views)} izlenme</p><p class="prose">Video kaynağı henüz eklenmedi. Şimdilik diğer videoları keşfedebilirsin.</p><button class="button" data-sheet-close>Videolara dön</button></div>`);}
const ctx={recipes:DATA.recipes,day:DATA.recipes.find(r=>r.slug===DATA.daySlug)||DATA.recipes[0],videos:WEB.videos,photo:picture,icon,esc,detail,camera,openVideo,searchHTML,sheet,mealFor:r=>recipeInfo(r).facets?.ogun||[]};
const main=q('.home-editorial'),featured=q('.featured-block');
featured.classList.remove('reveal');featured.classList.add('six-module');featured.dataset.sixBlock='recipes';
q('.block-heading',featured).innerHTML=`<div><span class="eyebrow">Tarifler</span><h2>Bu hafta öne çıkanlar</h2></div><a href="liste-1.html" class="see-all" aria-label="Tüm tarifler">Tümünü gör ${icon('arrow')}</a>`;
all('.weekly-card',featured).forEach((el,i)=>{const img=q('[data-photo-src]',el);img.dataset.photoSrc=DATA.recipes[i].image;img.style.backgroundImage=`url('${DATA.recipes[i].image}')`;});
main.replaceChildren();
const hero=document.createElement('section');hero.className=`six-hero hero-${mode}`;hero.dataset.sixBlock='hero';hero.innerHTML=SIX_HERO.render(mode,ctx);main.append(hero);
const body=document.createElement('div');body.className='six-content';main.append(body);
const cats=document.createElement('section');cats.className='six-module six-categories';cats.dataset.sixBlock='categories';
cats.innerHTML=`<div class="section-heading-row six-heading"><h2>Kategoriler & Dünya Mutfakları</h2><button class="icon-button" data-six-category-toggle aria-label="Dünya mutfaklarını göster" aria-pressed="false">${icon('swap')}</button></div><div class="six-category-rail" aria-label="Kategoriler"></div>`;
body.append(cats,featured);
function categoryRail(cuisines=false){const rail=q('.six-category-rail');const opts=PARITY.list.groups.find(g=>g.key==='mutfak')?.options||[];rail.innerHTML=cuisines?opts.map(o=>`<a class="six-category" href="liste-1.html?mutfak%5B%5D=${encodeURIComponent(o.value)}"><span class="six-category-icon">${icon('utensils')}</span><span>${esc(o.label.replace(/\s+[\d.,]+\s*$/,''))}</span></a>`).join(''):WEB.categories.map(c=>`<a class="six-category" href="liste-1.html?kategori=${encodeURIComponent(c.name)}">${c.image?picture(c.image):`<span class="six-category-icon">${icon('bowl')}</span>`}<span>${esc(c.name)}</span></a>`).join('');rail.scrollLeft=0;rail.setAttribute('aria-label',cuisines?'Dünya mutfakları':'Kategoriler');}
categoryRail();
const fridge=document.createElement('section');fridge.className='six-module six-fridge';fridge.dataset.sixBlock='fridge';
fridge.innerHTML=`<div class="six-fridge-title"><span class="six-symbol">${icon('fridge')}</span><div><h2>Dolapta Ne Var</h2><p>Dolaptakiler · Hariç tuttuklarım</p></div><button class="icon-button" data-six-fridge aria-label="Dolapta Ne Var aç">${icon('arrow')}</button></div><div class="six-fridge-chips">${['Tavuk','Patates','Yumurta'].map(n=>`<button class="chip" data-widget-ingredient="${n}" aria-pressed="false">${icon('plus')}${n}</button>`).join('')}<button class="chip" data-widget-all>Malzemeler ${icon('plus')}</button></div><div class="six-fridge-bottom"><output id="widgetCount" aria-live="polite">0 malzeme seçildi</output><button class="button" data-six-fridge-find>Tarifleri bul ${icon('arrow')}</button></div>`;
body.append(fridge);
function videoCard(v,i,large=false){return `<button class="six-video-card ${large?'is-featured':''}" data-six-video="${i}" aria-label="${esc(v.title)} videosunu aç"><span class="six-video-picture">${picture(v.image)}<span class="six-play">${icon('play')}</span><span class="six-duration">${esc(v.time)}</span></span><span class="six-video-copy"><strong>${esc(v.title)}</strong><span>${icon('eye')} ${esc(v.views)} izlenme</span></span></button>`;}
const videos=document.createElement('section');videos.className='six-module six-videos';videos.dataset.sixBlock='videos';videos.innerHTML=heading('Video Mutfağı','','Tümü','data-six-videos')+videoCard(WEB.videos[0],0,true)+`<div class="six-video-rail">${WEB.videos.slice(1).map((v,i)=>videoCard(v,i+1)).join('')}</div>`;body.append(videos);
const chefs=document.createElement('section');chefs.className='six-module six-chefs';chefs.dataset.sixBlock='chefs';chefs.innerHTML=heading('Şefler','','Tümü','data-six-chefs')+`<p class="six-chef-intro">Tariflerinin arkasındaki isimlerle tanış.</p><div class="six-creator-rail">${WEB.chefs.map((c,i)=>`<article class="six-creator"><button class="six-creator-identity" data-six-chef="${i}" aria-label="${esc(c.name)} profilini aç"><span class="six-creator-monogram"><span class="avatar">${esc(c.name.split(' ').map(n=>n[0]).slice(0,2).join(''))}</span><span class="six-creator-count"><b>${esc(c.count.split(' ')[0])}</b><small>tarif</small></span></span><strong>${esc(c.name)}</strong></button><button class="six-follow" data-six-follow="${i}" aria-pressed="false">${icon('plus')} Takip Et</button></article>`).join('')}</div>`;body.append(chefs);
const community=document.createElement('section');community.className='six-module six-community';community.dataset.sixBlock='community';community.innerHTML=`<span class="eyebrow">Topluluğa Katıl</span><h2>Senin de bir tarifin var</h2><p class="prose">Tariflerini paylaş, denendikçe puan topla, mutfak defterini herkesle buluştur.</p><button class="button" data-six-share>${icon('plus')} Tarifini Paylaş</button>`;body.append(community);
const top=q('.topbar');top.innerHTML=`<a class="brand-logo" href="${filename}" aria-label="DadaGastro ana sayfa"><img src="assets/marka/dadagastro-beyaz.svg?v=e9f2b47f6c7b" alt="DadaGastro"></a><div class="top-actions"><button class="icon-button" data-six-notifications aria-label="Bildirimler">${icon('bell')}</button><button class="icon-button" data-site-menu aria-label="Menü">${icon('menu')}</button></div>`;
const nav=all('.bottom-nav .nav-item');nav[0].href=filename;nav[1].href='liste-1.html';nav[3].innerHTML=icon('tip')+'<span>Püf Noktaları</span>';nav[3].setAttribute('data-six-tips','');
function connect(root=document){all('a[href],form[action]',root).forEach(a=>{const attr=a.tagName==='FORM'?'action':'href',h=a.getAttribute(attr)||'';let n=h.replace(/^tarifler\.html/,'liste-1.html').replace(/^tarif-detay\.html/,'detay-1.html').replace(/^index\.html/,filename);if(n.startsWith('tabaktan-tarif.html'))n=camera;if(n!==h)a.setAttribute(attr,n);});all('.photo-entry-options .action-card',root).forEach(a=>{const title=q('.action-card-title',a)?.textContent.trim();if(title==='Ne Pişirsem')a.setAttribute('data-six-ask','');if(title==='Dolapta Ne Var')a.setAttribute('data-six-fridge','');});}
connect();new MutationObserver(()=>connect()).observe(document.body,{childList:true,subtree:true});
function fridgeSheet(){sheet('Dolapta Ne Var',`<p class="prose">Bu önizlemede mevcut tariflerin malzemeleri seçilebilir.</p><div class="widget-ingredient-list">${['Tavuk','Patates','Yumurta','Limon','Tuz','Zeytinyağı','Su'].map(n=>`<button class="chip" data-widget-ingredient="${n}" aria-pressed="${widgetIngredients.has(n)}">${n}</button>`).join('')}</div><div class="sheet-actions"><button class="button secondary" data-widget-all>Malzemeler</button><button class="button" data-six-fridge-find>Tarifleri bul</button></div>`);}
function tips(){sheet('Püf Noktaları',`<div class="action-card-list">${HOME_MEDIA.tips.map(t=>actionCard({title:t.title,symbol:'tip',description:t.reads,attrs:'data-six-soon'})).join('')}</div>`);}
function ask(){sheet('Ne Pişirsem',`<div class="action-card-list">${actionCard({title:'Tarif Ara',symbol:'search',description:'Öğün · Süre · Zorluk',href:'liste-1.html'})}${actionCard({title:'Dolapta Ne Var',symbol:'fridge',description:'Dolaptakiler · Hariç tuttuklarım',attrs:'data-six-fridge'})}${actionCard({title:'Yemek Modu',symbol:'bowl',description:'Hazır Menüler · Sıfırdan Kur',attrs:'data-six-soon'})}</div>`);}
document.addEventListener('click',e=>{const t=e.target;
 const clear=t.closest('[data-six-clear]');if(clear){const input=q('input',clear.form);input.value='';clear.hidden=true;input.focus();return;}
 if(t.closest('[data-six-category-toggle]')){const b=t.closest('button'),on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',on);b.setAttribute('aria-label',on?'Kategorileri göster':'Dünya mutfaklarını göster');categoryRail(on);}
 const v=t.closest('[data-six-video]');if(v){e.preventDefault();e.stopImmediatePropagation();openVideo(Number(v.dataset.sixVideo));return;}
 if(t.closest('[data-six-videos]')){e.preventDefault();e.stopImmediatePropagation();sheet('Video Mutfağı',`<div class="six-video-sheet">${WEB.videos.map((v,i)=>videoCard(v,i)).join('')}</div>`);return;}
 if(t.closest('[data-six-fridge]')){e.preventDefault();e.stopImmediatePropagation();fridgeSheet();return;}
 if(t.closest('[data-six-fridge-find]')){e.preventDefault();e.stopImmediatePropagation();if(widgetIngredients.size)location.href='liste-1.html?malzeme='+encodeURIComponent([...widgetIngredients].join(','));else toast('Önce bir malzeme seç.');return;}
 if(t.closest('[data-six-tips]')){e.preventDefault();e.stopImmediatePropagation();tips();return;}
 if(t.closest('[data-six-ask]')){e.preventDefault();e.stopImmediatePropagation();ask();return;}
 if(t.closest('[data-six-soon]')){e.preventDefault();e.stopImmediatePropagation();toast('Yakında');return;}
 const follow=t.closest('[data-six-follow]');if(follow){e.preventDefault();e.stopImmediatePropagation();if(!memberPreview()){gate('Şefi takip et');return;}const on=follow.getAttribute('aria-pressed')!=='true';follow.setAttribute('aria-pressed',on);follow.innerHTML=icon(on?'check':'plus')+(on?' Takip ediliyor':' Takip Et');toast(on?'Önizleme: şef takip edildi.':'Önizleme: takip kaldırıldı.');return;}
 if(t.closest('[data-six-share]')){e.preventDefault();e.stopImmediatePropagation();if(!memberPreview())gate('Tarifini Paylaş');else toast('Tarif ekleme ekranı yakında; bu bir önizlemedir.');return;}
 const chef=t.closest('[data-six-chef]');if(chef){e.preventDefault();e.stopImmediatePropagation();const c=WEB.chefs[Number(chef.dataset.sixChef)];sheet(c.name,`<p>${esc(c.count)}</p><p class="prose">Şef profili yakında.</p><button class="button" data-six-follow="${chef.dataset.sixChef}">${icon('plus')} Takip Et</button>`);return;}
 if(t.closest('[data-six-chefs]')){e.preventDefault();e.stopImmediatePropagation();sheet('Şefler',`<div class="action-card-list">${WEB.chefs.map((c,i)=>actionCard({title:c.name,symbol:'user',description:c.count,attrs:`data-six-chef="${i}"`})).join('')}</div>`);return;}
 if(t.closest('[data-six-notifications]')){e.preventDefault();e.stopImmediatePropagation();if(!memberPreview())gate('Bildirimler');else sheet('Bildirimler','<p class="prose">Bildirim ekranı yakında.</p><button class="button" data-sheet-close>Kapat</button>');}
},true);
document.addEventListener('input',e=>{if(e.target.matches('.six-search input'))q('[data-six-clear]',e.target.form).hidden=!e.target.value;});
// Replace only this composition's header geometry; keep original components and drawer runtime.
const oldSync=syncHeader;removeEventListener('scroll',oldSync);removeEventListener('resize',oldSync);document.removeEventListener('scroll',oldSync,true);visualViewport?.removeEventListener('scroll',oldSync);headerGeometryObserver.disconnect();motion.removeEventListener('change',oldSync);
syncHeader=function(){const h=top.getBoundingClientRect(),first=q('.six-hero-group',hero),r=first?.getBoundingClientRect();const limit=Math.max(1,(r?.top||100)+scrollY-h.height-8);const alpha=motion.matches?Number(scrollY>=Math.min(48,limit)):Math.min(1,scrollY/Math.min(48,limit));top.style.setProperty('background-color',`color-mix(in srgb,var(--tomato) ${alpha*100}%,transparent)`,'important');top.dataset.alpha=alpha.toFixed(3);top.classList.toggle('is-solid',alpha>=.999);for(const g of all('.six-hero-group',hero)){const rect=g.getBoundingClientRect();g.style.visibility=rect.top<h.bottom+8?'hidden':'';}};
function syncHeroVeils(){
 const pairs=[['.six-cinema-image','.six-cinema-copy'],['.six-video-feature','.six-video-copy'],['.six-day-card','.six-day-copy'],['.six-discovery-tile','.six-discovery-copy'],['.six-story-cover','.six-story-copy']];
 for(const [imageSel,copySel] of pairs)for(const box of all(imageSel,hero)){const copy=q(copySel,box);if(!copy)continue;const y=copy.getBoundingClientRect().top-box.getBoundingClientRect().top;const head=box.matches('.six-cinema-image,.six-video-feature');
 const pts=head?[[0,76],[48,72],[Math.max(64,y-144),35],[Math.max(80,y-120),28],[Math.max(96,y-96),40],[Math.max(112,y-72),52],[Math.max(128,y-48),66],[Math.max(144,y-24),86],[Math.max(160,y),90]]:[[Math.max(0,y-192),0],[Math.max(0,y-168),3],[Math.max(0,y-144),8],[Math.max(0,y-120),16],[Math.max(0,y-96),28],[Math.max(0,y-72),44],[Math.max(0,y-48),64],[Math.max(0,y-24),86],[y,90]];
 box.style.setProperty('--six-image-veil','linear-gradient(to bottom,'+pts.map(([stop,a])=>`color-mix(in srgb,var(--overlay) ${a}%,transparent) ${stop}px`).join(',')+',var(--overlay) 100%)');}
}
addEventListener('resize',syncHeroVeils);addEventListener('six:layout',syncHeroVeils);document.fonts.ready.then(syncHeroVeils);
addEventListener('scroll',syncHeader,{passive:true});addEventListener('resize',syncHeader);addEventListener('six:layout',()=>{syncHeader();applyProse(hero);});motion.addEventListener('change',syncHeader);
SIX_HERO.bind(mode,ctx);hydratePhotos(body);applyTypeRoles(body);applyProse(body);document.fonts.ready.then(()=>{syncHeader();syncPhotoReadability();});syncHeader();
})();
